//! Permutations of slot positions, and permutations paired with a sign.
//!
//! A [`Perm`] is a bijection on `{0, .., n-1}` in one-line notation. A
//! [`SignedPerm`] additionally carries `sign in {+1, -1}`: the factor a
//! tensor component picks up when its slots are reordered by `perm`. This is
//! the representation used both for [`crate::symmetry::SymmetryGroup`]
//! generators and, in `oderom-canon`, for elements of the Butler-Portugal
//! search group.

use smallvec::SmallVec;

/// A bijection on `{0, .., n-1}`, stored as the image of each point
/// (one-line notation): `image(i)` is where point `i` is sent.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct Perm(SmallVec<[u16; 12]>);

impl Perm {
    /// The identity permutation on `n` points.
    pub fn identity(n: usize) -> Self {
        Perm((0..n as u16).collect())
    }

    /// Builds a permutation from an explicit image table. Panics (debug
    /// only, via the caller's validation) is not performed here; callers
    /// that need validation should use [`Perm::try_from_images`].
    pub fn from_images(images: impl Into<SmallVec<[u16; 12]>>) -> Self {
        Perm(images.into())
    }

    /// Builds a permutation from an image table, checking it is a bijection
    /// on `0..images.len()`.
    pub fn try_from_images(images: &[u16]) -> Option<Self> {
        let n = images.len();
        let mut seen = vec![false; n];
        for &x in images {
            let x = x as usize;
            if x >= n || seen[x] {
                return None;
            }
            seen[x] = true;
        }
        Some(Perm(images.iter().copied().collect()))
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The image of point `i` under this permutation.
    pub fn image(&self, i: u16) -> u16 {
        self.0[i as usize]
    }

    pub fn as_slice(&self) -> &[u16] {
        &self.0
    }

    pub fn is_identity(&self) -> bool {
        self.0.iter().enumerate().all(|(i, &x)| i as u16 == x)
    }

    /// `self.then(other)` is the permutation obtained by applying `self`
    /// first and `other` second: `(self.then(other))(i) = other(self(i))`.
    pub fn then(&self, other: &Perm) -> Perm {
        debug_assert_eq!(self.len(), other.len());
        Perm(self.0.iter().map(|&x| other.image(x)).collect())
    }

    pub fn inverse(&self) -> Perm {
        let mut inv: SmallVec<[u16; 12]> = smallvec::smallvec![0; self.0.len()];
        for (i, &img) in self.0.iter().enumerate() {
            inv[img as usize] = i as u16;
        }
        Perm(inv)
    }

    /// The permutation swapping `a` and `b` and fixing everything else.
    pub fn transposition(n: usize, a: u16, b: u16) -> Self {
        let mut images: SmallVec<[u16; 12]> = (0..n as u16).collect();
        images.swap(a as usize, b as usize);
        Perm(images)
    }

    /// Sign of the permutation itself (+1 even, -1 odd), computed by
    /// counting transpositions via cycle decomposition. This is the
    /// combinatorial parity of `self`, unrelated to the `sign` field of a
    /// [`SignedPerm`] (which is separate data attached by a generator).
    pub fn parity(&self) -> i8 {
        let n = self.0.len();
        let mut visited = vec![false; n];
        let mut sign = 1i8;
        for start in 0..n {
            if visited[start] {
                continue;
            }
            let mut len = 0;
            let mut cur = start;
            while !visited[cur] {
                visited[cur] = true;
                cur = self.0[cur] as usize;
                len += 1;
            }
            if len % 2 == 0 {
                sign = -sign;
            }
        }
        sign
    }
}

/// A permutation together with the sign a tensor component picks up when
/// its slots are permuted this way. Composition multiplies signs; this
/// makes `SignedPerm` under [`SignedPerm::then`] a faithful representation
/// of the abstract group `Perm(n) x {+1,-1}` restricted to the subgroup
/// actually generated by a `TensorHead`'s declared symmetries.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct SignedPerm {
    pub perm: Perm,
    pub sign: i8,
}

impl SignedPerm {
    pub fn identity(n: usize) -> Self {
        SignedPerm { perm: Perm::identity(n), sign: 1 }
    }

    pub fn new(perm: Perm, sign: i8) -> Self {
        debug_assert!(sign == 1 || sign == -1);
        SignedPerm { perm, sign }
    }

    /// Apply `self` first, then `other`; signs multiply.
    pub fn then(&self, other: &SignedPerm) -> SignedPerm {
        SignedPerm { perm: self.perm.then(&other.perm), sign: self.sign * other.sign }
    }

    pub fn inverse(&self) -> SignedPerm {
        // sign in {+1,-1} is its own inverse, so the inverse element keeps it.
        SignedPerm { perm: self.perm.inverse(), sign: self.sign }
    }

    pub fn is_identity(&self) -> bool {
        self.sign == 1 && self.perm.is_identity()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_is_identity() {
        let id = Perm::identity(5);
        assert!(id.is_identity());
        for i in 0..5u16 {
            assert_eq!(id.image(i), i);
        }
    }

    #[test]
    fn then_composes_left_to_right() {
        // a = (0 1), b = (1 2); a.then(b) applies a first, then b.
        let a = Perm::transposition(3, 0, 1);
        let b = Perm::transposition(3, 1, 2);
        let ab = a.then(&b);
        // 0 -a-> 1 -b-> 2
        assert_eq!(ab.image(0), 2);
        // 1 -a-> 0 -b-> 0
        assert_eq!(ab.image(1), 0);
        // 2 -a-> 2 -b-> 1
        assert_eq!(ab.image(2), 1);
    }

    #[test]
    fn inverse_undoes_then() {
        let p = Perm::try_from_images(&[2, 0, 3, 1]).unwrap();
        let inv = p.inverse();
        assert!(p.then(&inv).is_identity());
        assert!(inv.then(&p).is_identity());
    }

    #[test]
    fn associativity_holds() {
        let a = Perm::try_from_images(&[1, 0, 2, 3]).unwrap();
        let b = Perm::try_from_images(&[0, 2, 1, 3]).unwrap();
        let c = Perm::try_from_images(&[3, 1, 2, 0]).unwrap();
        let lhs = a.then(&b).then(&c);
        let rhs = a.then(&b.then(&c));
        assert_eq!(lhs, rhs);
    }

    #[test]
    fn transposition_parity_is_odd() {
        assert_eq!(Perm::transposition(4, 0, 1).parity(), -1);
        assert_eq!(Perm::identity(4).parity(), 1);
    }

    #[test]
    fn signed_perm_inverse_keeps_sign() {
        let g = SignedPerm::new(Perm::transposition(4, 0, 1), -1);
        let inv = g.inverse();
        assert_eq!(inv.sign, -1);
        let id = g.then(&inv);
        assert!(id.perm.is_identity());
        assert_eq!(id.sign, 1);
    }

    #[test]
    fn try_from_images_rejects_non_bijections() {
        assert!(Perm::try_from_images(&[0, 0]).is_none());
        assert!(Perm::try_from_images(&[0, 2]).is_none());
        assert!(Perm::try_from_images(&[0, 1]).is_some());
    }
}
