//! `oderom-canon` -- Marco 1.3: Butler-Portugal canonicalization of a
//! single [`Monomial`]'s contraction graph.
//!
//! The canonical form is the lexicographically minimal word (see
//! [`word::compute_word`]) reachable by acting on the monomial's slots
//! with the group generated by every factor's own declared symmetry,
//! combined with the freedom to permute factors that share a head (tensor
//! components commute). If that minimal word is reachable with both signs
//! +1 and -1, the monomial equals its own negative and is
//! [`CanonResult::Zero`].
//!
//! Multi-term identities (Bianchi and friends) are out of scope: they do
//! not form a group, so no coset search finds them. See the `#[ignore]`d
//! tests below for the documented, deliberately-unimplemented behavior.

mod coset;
mod error;
mod word;

pub use error::CanonError;

use oderom_core::{Factor, Matching, Monomial, Registry, Scalar, SlotId};
use rustc_hash::FxHashMap;
use smallvec::SmallVec;
use word::Layout;

#[derive(Clone, Debug)]
pub struct Canonical {
    pub monomial: Monomial,
    pub perm: oderom_core::Perm,
    pub sign: i8,
}

#[derive(Clone, Debug)]
pub enum CanonResult {
    Zero,
    Value(Canonical),
}

fn point_to_slot(p: u16, layout: &Layout) -> SlotId {
    let k = match layout.block_start.binary_search(&p) {
        Ok(k) => k,
        Err(k) => k - 1,
    };
    SlotId { factor: k as u16, slot: (p - layout.block_start[k]) as u8 }
}

/// Computes the canonical form of `m`. See the module documentation for
/// what "canonical" means and how zero is detected.
pub fn canonicalize(m: &Monomial, registry: &Registry) -> Result<CanonResult, CanonError> {
    let layout = word::build_layout(m, registry);
    let labeling = word::build_labeling(m, &layout);
    let generators = word::build_generators(m, registry, &layout);
    let bsgs = oderom_core::Bsgs::from_generators(layout.degree, &generators);

    let result = coset::search_minimal(&bsgs, &labeling);
    if result.is_zero {
        return Ok(CanonResult::Zero);
    }
    let g = &result.representative;

    let canonical_factors: SmallVec<[Factor; 4]> = layout
        .canon_factor_order
        .iter()
        .map(|&f| Factor { head: m.factors()[f].head })
        .collect();

    let factor_to_block: FxHashMap<usize, usize> =
        layout.canon_factor_order.iter().enumerate().map(|(k, &f)| (f, k)).collect();
    let mut new_pairs = Vec::with_capacity(m.contractions().len());
    for &(a, b) in m.contractions().pairs() {
        let pa = g.perm.image(layout.point_of(&factor_to_block, a));
        let pb = g.perm.image(layout.point_of(&factor_to_block, b));
        new_pairs.push((point_to_slot(pa, &layout), point_to_slot(pb, &layout)));
    }
    let mut new_free = Vec::with_capacity(m.free().len());
    for (slot, label) in m.free() {
        let p = g.perm.image(layout.point_of(&factor_to_block, *slot));
        new_free.push((point_to_slot(p, &layout), label.clone()));
    }

    let new_coeff = m.coeff() * Scalar::from_int(g.sign as i64);
    let monomial = Monomial::try_new(
        new_coeff,
        canonical_factors,
        Matching::try_new(new_pairs)?,
        new_free,
        registry,
    )?;

    Ok(CanonResult::Value(Canonical { monomial, perm: g.perm.clone(), sign: g.sign }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use oderom_core::{AbstractIndex, HeadId, Perm, SignedPerm, SlotSig, Variance};

    struct Prelude {
        registry: Registry,
        riemann: HeadId,
        levi_civita_3: HeadId,
    }

    fn standard_prelude() -> Prelude {
        let mut reg = Registry::new();
        let m = reg.declare_manifold("M", 4).unwrap();
        let tm = reg.declare_bundle("TM", m, 4).unwrap();
        let co = |dim| SlotSig { bundle: tm, variance: Variance::Co, dim };

        let riemann_slots: SmallVec<[SlotSig; 4]> =
            smallvec::smallvec![co(4), co(4), co(4), co(4)];
        let pair_swap = SignedPerm::new(Perm::try_from_images(&[2, 3, 0, 1]).unwrap(), 1);
        let riemann_gens = vec![
            SignedPerm::new(Perm::transposition(4, 0, 1), -1),
            SignedPerm::new(Perm::transposition(4, 2, 3), -1),
            pair_swap,
        ];
        let riemann = reg.declare_head("R", riemann_slots, riemann_gens).unwrap();

        let metric_slots: SmallVec<[SlotSig; 4]> = smallvec::smallvec![co(4), co(4)];
        let metric_gens = vec![SignedPerm::new(Perm::transposition(2, 0, 1), 1)];
        reg.declare_head("g", metric_slots, metric_gens).unwrap();

        let eps_slots: SmallVec<[SlotSig; 4]> = smallvec::smallvec![co(3), co(3), co(3)];
        let eps_gens = oderom_core::totally_antisymmetric_generators(3);
        let levi_civita_3 = reg.declare_head("eps", eps_slots, eps_gens).unwrap();

        Prelude { registry: reg, riemann, levi_civita_3 }
    }

    fn free(factor: u16, slot: u8, name: &str) -> (SlotId, AbstractIndex) {
        (SlotId { factor, slot }, AbstractIndex::new(name))
    }

    fn riemann_free(p: &Prelude, order: [&str; 4]) -> Monomial {
        let factors = smallvec::smallvec![Factor { head: p.riemann }];
        let free = vec![
            free(0, 0, order[0]),
            free(0, 1, order[1]),
            free(0, 2, order[2]),
            free(0, 3, order[3]),
        ];
        Monomial::try_new(Scalar::ONE, factors, Matching::default(), free, &p.registry).unwrap()
    }

    #[test]
    fn r_abcd_and_r_cdab_have_same_canonical_form_and_sign() {
        let p = standard_prelude();
        let m1 = riemann_free(&p, ["a", "b", "c", "d"]);
        // R[c,d,a,b]: slot0='c', slot1='d', slot2='a', slot3='b'.
        let m2 = riemann_free(&p, ["c", "d", "a", "b"]);
        let c1 = canonicalize(&m1, &p.registry).unwrap();
        let c2 = canonicalize(&m2, &p.registry).unwrap();
        match (c1, c2) {
            (CanonResult::Value(a), CanonResult::Value(b)) => {
                assert_eq!(a.monomial.coeff(), b.monomial.coeff());
                assert_eq!(a.sign, 1);
                assert_eq!(b.sign, 1);
                assert_eq_free_layout(&a.monomial, &b.monomial);
            }
            _ => panic!("expected both nonzero"),
        }
    }

    #[test]
    fn r_abcd_and_r_bacd_have_opposite_sign() {
        let p = standard_prelude();
        let m1 = riemann_free(&p, ["a", "b", "c", "d"]);
        let m2 = riemann_free(&p, ["b", "a", "c", "d"]);
        let c1 = canonicalize(&m1, &p.registry).unwrap();
        let c2 = canonicalize(&m2, &p.registry).unwrap();
        match (c1, c2) {
            (CanonResult::Value(a), CanonResult::Value(b)) => {
                assert_eq_free_layout(&a.monomial, &b.monomial);
                assert_eq!(a.monomial.coeff(), Scalar::ONE);
                assert_eq!(b.monomial.coeff(), Scalar::new(-1, 1));
            }
            _ => panic!("expected both nonzero"),
        }
    }

    #[test]
    fn r_abab_and_r_cdcd_are_identical_since_dummies_are_edges() {
        let p = standard_prelude();
        let build = |a: &str, b: &str| {
            let factors = smallvec::smallvec![Factor { head: p.riemann }];
            let contractions = Matching::try_new([
                (SlotId { factor: 0, slot: 0 }, SlotId { factor: 0, slot: 2 }),
                (SlotId { factor: 0, slot: 1 }, SlotId { factor: 0, slot: 3 }),
            ])
            .unwrap();
            let _ = (a, b);
            Monomial::try_new(Scalar::ONE, factors, contractions, vec![], &p.registry).unwrap()
        };
        let m1 = build("a", "b");
        let m2 = build("c", "d"); // dummy *names* never appear in the structure at all
        let c1 = canonicalize(&m1, &p.registry).unwrap();
        let c2 = canonicalize(&m2, &p.registry).unwrap();
        match (c1, c2) {
            (CanonResult::Value(a), CanonResult::Value(b)) => {
                assert_eq!(a.monomial.coeff(), b.monomial.coeff());
                assert_eq!(a.monomial.contractions(), b.monomial.contractions());
            }
            _ => panic!("expected both nonzero"),
        }
    }

    #[test]
    fn epsilon_contracted_with_symmetric_tensor_is_zero() {
        let p = standard_prelude();
        // A symmetric rank-2 head T (reuse the metric's own declaration
        // shape: symmetric under (0 1)+).
        let t_slots: SmallVec<[SlotSig; 4]> = smallvec::smallvec![
            SlotSig { bundle: p.registry.lookup_bundle("TM").unwrap(), variance: Variance::Co, dim: 4 },
            SlotSig { bundle: p.registry.lookup_bundle("TM").unwrap(), variance: Variance::Co, dim: 4 },
        ];
        // eps has 3 indices of a 3-dim bundle; reuse metric's bundle isn't
        // dimensionally sound but oderom-core/canon do not check dimension
        // consistency (that is out of scope for Marco 1 type checking, and
        // irrelevant to the pure combinatorics being tested here).
        let mut p = p;
        let t = p.registry.declare_head(
            "T",
            t_slots,
            vec![SignedPerm::new(Perm::transposition(2, 0, 1), 1)],
        ).unwrap();

        let factors = smallvec::smallvec![Factor { head: p.levi_civita_3 }, Factor { head: t }];
        let contractions = Matching::try_new([
            (SlotId { factor: 0, slot: 0 }, SlotId { factor: 1, slot: 0 }),
            (SlotId { factor: 0, slot: 1 }, SlotId { factor: 1, slot: 1 }),
        ])
        .unwrap();
        let free = vec![free(0, 2, "c")];
        let m = Monomial::try_new(Scalar::ONE, factors, contractions, free, &p.registry).unwrap();

        let result = canonicalize(&m, &p.registry).unwrap();
        assert!(matches!(result, CanonResult::Zero));
    }

    /// Reduction of `R[a,b,c,d] g[a,c] g[b,d]` to the same canonical form
    /// as `R[a,b,a,b]` requires substituting each metric contraction away
    /// (index lowering through an *explicit* metric), which is explicit-
    /// metric algebra -- Marco 2 territory per DESIGN.md -- not a
    /// permutation symmetry of the monomial's own contraction graph. Pure
    /// Butler-Portugal canonicalization cannot change a term's factor
    /// count. Left `#[ignore]`d and flagged to the user rather than
    /// guessed at silently.
    #[test]
    #[ignore = "requires metric-contraction substitution, out of Marco 1 scope per DESIGN.md; flagged to user"]
    fn riemann_contracted_through_explicit_metric_reduces_like_direct_contraction() {
        unimplemented!()
    }

    fn assert_eq_free_layout(a: &Monomial, b: &Monomial) {
        let mut fa: Vec<_> = a.free().iter().map(|(s, l)| (*s, l.clone())).collect();
        let mut fb: Vec<_> = b.free().iter().map(|(s, l)| (*s, l.clone())).collect();
        fa.sort_by_key(|(s, _)| *s);
        fb.sort_by_key(|(s, _)| *s);
        assert_eq!(fa, fb);
    }
}
